---
- name: Creating a cronjob
  hosts: pfsense_group
  become: yes
  tasks:
    - name: pfSense reboot
      cron:
        name: pfsense reboot
        minute: "16"
        hour: "14"
        day: "*"
        month: "*"
        weekday: "*"
        user: root
        job: "reboot"
