---
- name: Creating a cronjob
  hosts: pfsense_group
  become: yes
  tasks:
    - name: e2guardina restart
      cron:
        name: restart e2guardian service
        minute: "53"
        hour: "20"
        day: "*"
        month: "*"
        weekday: "*"
        user: root
        job: "pfSsh.php playback svc restart e2guardian & echo $(date) >> /etc/ansible/pfsense_playbook/roles/e2g/files/logs.txt"
