#pfsense playbook

- name: pfSense 2.7.2 Playbook
  hosts: pfsense_group
  gather_facts: False
  roles:
    - backup
    #- alias
    #- rules
    #- update
    #- common
    #- reboot_system
    #- e2g
